name: Build

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain --no-daemon

      - name: Test
        run: ./gradlew test --no-daemon
